use_frameworks!

platform :ios, '8.0'

target 'PMAuthorKit_Category_Example' do
  pod 'PMAuthorKit_Category', :path => '../'

  target 'PMAuthorKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
